module.exports = {
  extends: [
    "stylelint-config-recommended-scss",
    "stylelint-config-prettier-scss",
    "stylelint-config-idiomatic-order",
  ],
  plugins: ["stylelint-order"],
  ignoreFiles: ["build/**/*.css"],
  rules: {
    "at-rule-no-unknown": null,
    "at-rule-empty-line-before": null,
    "at-rule-name-space-after": "always",
    "at-rule-no-vendor-prefix": true,
    "at-rule-semicolon-space-before": "never",
    "block-closing-brace-empty-line-before": null,
    "block-closing-brace-newline-after": null,
    "block-opening-brace-space-before": null,
    "color-hex-length": "long",
    "color-named": "never",
    "no-empty-source": true,
    "declaration-block-semicolon-newline-after": "always-multi-line",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-colon-newline-after": null,
    "declaration-colon-space-after": "always",
    "declaration-empty-line-before": null,
    "font-family-name-quotes": "always-unless-keyword",
    "font-weight-notation": [
      "numeric",
      {
        ignore: ["relative"],
      },
    ],
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "length-zero-no-unit": true,
    "max-empty-lines": 2,
    "max-line-length": null,
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-parentheses-space-inside": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "never",
    "no-descending-specificity": null,
    "no-duplicate-selectors": true,
    "media-feature-name-no-unknown": [
      true,
      {
        ignoreMediaFeatureNames: ["prefers-reduced-motion"],
      },
    ],
    "property-no-unknown": true,
    "property-no-vendor-prefix": true,
    "rule-empty-line-before": null,
    "scss/at-rule-no-unknown": true,
    "scss/media-feature-value-dollar-variable": "always",
    "selector-attribute-quotes": "always",
    "selector-descendant-combinator-no-non-space": null,
    "selector-list-comma-newline-after": "always",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never-single-line",
    "selector-max-empty-lines": 1,
    "selector-max-specificity": null,
    "selector-max-universal": 1,
    "selector-pseudo-class-no-unknown": [
      true,
      {
        ignorePseudoClasses: ["global"],
      },
    ],
    "selector-no-vendor-prefix": null,
    "string-quotes": "double",
    "value-list-comma-newline-after": null,
    "value-no-vendor-prefix": true,
    "scss/at-import-partial-extension": null,
  },
};
